version: '2'

services:
  danglong:
    image: 'danglong:latest'
    build:
      context: .
    container_name: danglong
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
      - mongo
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/test
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: danglong99
    restart:
      always
    networks:
      - danglong

  mysqldb:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=danglong99
      - MYSQL_DATABASE=test
    ports:
      - "3307:3306"
    networks:
      - danglong

  mongo:
    image: 'mongo'
    ports:
      - "27017:27017"
    networks:
      - danglong

networks:
  danglong: