name: CI/CD with Docker

on:
  push:
    branches: [ "main" ]   # chỉ chạy khi push lên nhánh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot jar
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t my-spring-app:latest .

      - name: Save Docker image to tar
        run: docker save my-spring-app:latest -o my-spring-app.tar

      - name: Copy Docker image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "my-spring-app.tar"
          target: "~/app"

      - name: Load and restart Docker container on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/app
            docker load -i my-spring-app.tar
            docker-compose down
            docker-compose up -d
